/* Neon Runner: original perspective-lane endless runner, drawn entirely with Canvas. */
'use strict';
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const ui={score:document.querySelector('#score'),coins:document.querySelector('#coins'),time:document.querySelector('#time'),heat:document.querySelector('#heat'),meter:document.querySelector('#heat-meter'),powerups:document.querySelector('#powerups'),toast:document.querySelector('#toast')};
const screens={menu:document.querySelector('#menu-screen'),how:document.querySelector('#how-screen'),pause:document.querySelector('#pause-screen'),over:document.querySelector('#over-screen')};
const game={state:'menu',w:0,h:0,dpr:1,last:0,time:0,coins:0,score:0,best:Number(localStorage.getItem('neon-runner-best')||0),speed:0.34,spawnIn:1,objects:[],particles:[],buildings:[],player:{lane:1,laneVisual:1,jump:0,slide:0,shield:0,magnet:0,boost:0},roadOffset:0,audio:null,toastTimer:0};
document.querySelector('#menu-best').textContent=game.best;
function resize(){const r=canvas.getBoundingClientRect();game.dpr=Math.min(devicePixelRatio||1,2);game.w=r.width;game.h=r.height;canvas.width=Math.round(r.width*game.dpr);canvas.height=Math.round(r.height*game.dpr);ctx.setTransform(game.dpr,0,0,game.dpr,0,0);makeBuildings();}
function makeBuildings(){game.buildings=[];for(let side=0;side<2;side++){let x=side?game.w*.72:-5;while(x<(side?game.w+25:game.w*.31)){const width=24+Math.random()*60,height=60+Math.random()*170;game.buildings.push({x,y:game.h*.37-height,width,height,side,lit:Math.random()});x+=width-3;}}}
function audio(){if(!game.audio){game.audio=new(window.AudioContext||window.webkitAudioContext)();}if(game.audio.state==='suspended')game.audio.resume();}
function beep(freq=520,duration=.09,type='sine',volume=.035){try{audio();const o=game.audio.createOscillator(),g=game.audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(volume,game.audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,game.audio.currentTime+duration);o.connect(g);g.connect(game.audio.destination);o.start();o.stop(game.audio.currentTime+duration);}catch(_){}}
function show(name){Object.entries(screens).forEach(([key,node])=>node.classList.toggle('hidden',key!==name));}
function startGame(){audio();Object.assign(game,{state:'playing',time:0,coins:0,score:0,speed:.34,spawnIn:.8,objects:[],particles:[],roadOffset:0});Object.assign(game.player,{lane:1,laneVisual:1,jump:0,slide:0,shield:0,magnet:0,boost:0});show(null);document.querySelector('#hud').style.display='grid';updateHud();}
function togglePause(){if(game.state==='playing'){game.state='paused';show('pause');}else if(game.state==='paused'){game.state='playing';show(null);game.last=performance.now();}}
function backToMenu(){game.state='menu';show('menu');document.querySelector('#hud').style.display='none';}
function act(action){if(game.state!=='playing')return;const p=game.player;if(action==='left')p.lane=Math.max(0,p.lane-1);if(action==='right')p.lane=Math.min(2,p.lane+1);if(action==='jump'&&p.jump<=0&&p.slide<=0){p.jump=.78;beep(360,.12,'triangle');}if(action==='slide'&&p.slide<=0&&p.jump<=0)p.slide=.72;}
function laneX(lane,depth){const horizon=game.h*.36,bottom=game.h*1.04,spread=game.w*.34;return game.w/2+(lane-1)*spread*(.12+.88*depth);}
function horizonY(depth){return game.h*.36+depth*game.h*.72;}
function addObject(type,lane,depth=-.04){game.objects.push({type,lane,depth,hit:false,phase:Math.random()*6.28});}
function spawnWave(){const heat=heatLevel();const roll=Math.random();if(roll<.44){const lane=Math.floor(Math.random()*3),type=roll<.13?'car':roll<.30?'barrier':'laser';addObject(type,lane);if(Math.random()<.44+heat*.025)for(let i=1;i<5;i++)addObject('coin',lane,-.05-i*.075);}
else if(roll<.78){const lane=Math.floor(Math.random()*3);for(let i=0;i<5;i++)addObject('coin',lane,-.04-i*.09);if(Math.random()<.52)addObject(Math.random()<.5?'shield':Math.random()<.5?'magnet':'boost',(lane+1+Math.floor(Math.random()*2))%3,-.24);}
else {const blocked=Math.floor(Math.random()*3);addObject(['barrier','car','laser'][Math.floor(Math.random()*3)],blocked);const safe=blocked===1?[0,2]:[1,blocked===0?2:0];const lane=safe[Math.floor(Math.random()*safe.length)];for(let i=0;i<3;i++)addObject('coin',lane,-.06-i*.09);}}
function heatLevel(){return Math.min(5,1+Math.floor(game.time/24));}
function update(dt){game.time+=dt;const heat=heatLevel(),p=game.player;game.speed=Math.min(.75,.34+game.time*.0022+(heat-1)*.018);const velocity=game.speed*(p.boost>0?1.5:1);game.roadOffset=(game.roadOffset+dt*velocity)%1;p.laneVisual+=(p.lane-p.laneVisual)*Math.min(1,dt*13);p.jump=Math.max(0,p.jump-dt);p.slide=Math.max(0,p.slide-dt);p.shield=Math.max(0,p.shield-dt);p.magnet=Math.max(0,p.magnet-dt);p.boost=Math.max(0,p.boost-dt);game.spawnIn-=dt;if(game.spawnIn<=0){spawnWave();game.spawnIn=Math.max(.52,1.1-heat*.075+Math.random()*.42);}
for(const o of game.objects){o.depth+=dt*velocity*(o.type==='coin'?.86:1);if(o.type==='coin'&&p.magnet>0&&o.lane===p.lane&&o.depth>.58){o.lane=p.lane+(p.laneVisual-(Math.round(p.laneVisual)));o.depth+=dt*.9;}
if(o.depth>.82&&!o.hit&&Math.abs(o.lane-p.laneVisual)<.46){if(o.type==='coin'){o.hit=true;game.coins++;game.score+=Math.round(100*(1+(heat-1)*.12)*(p.boost>0?2:1));burst(laneX(p.laneVisual,.91),horizonY(.91),'#ffe66d');beep(780,.08,'sine');}
else if(['shield','magnet','boost'].includes(o.type)){o.hit=true;if(o.type==='shield')p.shield=10;if(o.type==='magnet')p.magnet=9;if(o.type==='boost')p.boost=7;notify({shield:'護盾啟動',magnet:'磁力吸引',boost:'加速啟動'}[o.type]);beep(620,.18,'triangle',.05);}
else if(o.depth>.91&&o.depth<1.02){const avoided=o.type==='barrier'?p.jump>.18:o.type==='laser'?p.slide>.18:false;if(!avoided){if(p.shield>0){p.shield=0;o.hit=true;burst(laneX(p.laneVisual,.96),horizonY(.96),'#55f7ff');notify('護盾抵擋撞擊');beep(220,.2,'square');}else{endGame();return;}}else if(o.depth>.99)o.hit=true;}}
}
game.objects=game.objects.filter(o=>o.depth<1.15&&!o.hit);game.particles.forEach(q=>{q.x+=q.vx*dt;q.y+=q.vy*dt;q.life-=dt;});game.particles=game.particles.filter(q=>q.life>0);game.score+=dt*(10+heat*2)*(p.boost>0?2:1);updateHud();}
function updateHud(){const heat=heatLevel(),p=game.player;ui.score.textContent=Math.floor(game.score);ui.coins.textContent=game.coins;ui.time.textContent=formatTime(game.time);ui.heat.textContent=`LEVEL ${heat}`;ui.meter.style.width=`${heat*20}%`;ui.powerups.innerHTML=[p.shield>0?`🛡 護盾 ${Math.ceil(p.shield)}s`:null,p.magnet>0?`✦ 磁力 ${Math.ceil(p.magnet)}s`:null,p.boost>0?`⚡ 加速 ${Math.ceil(p.boost)}s`:null].filter(Boolean).join('<br>');}
function formatTime(seconds){return `${Math.floor(seconds/60)}:${String(Math.floor(seconds%60)).padStart(2,'0')}`;}
function burst(x,y,color){for(let i=0;i<13;i++){const a=Math.random()*Math.PI*2,s=25+Math.random()*90;game.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:.25+Math.random()*.35,color});}}
function notify(message){ui.toast.textContent=message;ui.toast.classList.add('show');clearTimeout(game.toastTimer);game.toastTimer=setTimeout(()=>ui.toast.classList.remove('show'),1300);}
function endGame(){game.state='over';beep(150,.42,'sawtooth',.06);game.best=Math.max(game.best,Math.floor(game.score));localStorage.setItem('neon-runner-best',game.best);document.querySelector('#final-score').textContent=Math.floor(game.score);document.querySelector('#final-coins').textContent=game.coins;document.querySelector('#final-time').textContent=formatTime(game.time);document.querySelector('#final-best').textContent=game.best;show('over');}
function polygon(points,fill,stroke=null,width=1){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=width;ctx.stroke();}}
function drawBackground(t){const w=game.w,h=game.h,sky=ctx.createLinearGradient(0,0,0,h);sky.addColorStop(0,'#080b21');sky.addColorStop(.52,'#231344');sky.addColorStop(1,'#080c20');ctx.fillStyle=sky;ctx.fillRect(0,0,w,h);const glow=ctx.createRadialGradient(w*.5,h*.39,5,w*.5,h*.39,w*.45);glow.addColorStop(0,'#ec49d52b');glow.addColorStop(1,'#0a0d2100');ctx.fillStyle=glow;ctx.fillRect(0,0,w,h);
ctx.fillStyle='#101632';for(const b of game.buildings){const drift=(game.roadOffset*80)%50,x=b.x+(b.side?-drift:drift);ctx.fillRect(x,b.y,b.width,b.height);ctx.fillStyle=`rgba(73,231,255,${.12+b.lit*.25})`;for(let wy=b.y+10;wy<b.y+b.height-6;wy+=13)for(let wx=x+7;wx<x+b.width-5;wx+=12)if(Math.sin(wx*2+wy*3)>.3)ctx.fillRect(wx,wy,3,5);ctx.fillStyle='#101632';}
ctx.fillStyle='#080b20';ctx.fillRect(0,h*.35,w,h*.65);polygon([[w*.5,h*.35],[w*.83,h],[w*.17,h]],'#11102b','#8c37a9',2);polygon([[w*.5,h*.35],[w*.17,h],[w*.5,h]],'#11142f');polygon([[w*.5,h*.35],[w*.83,h],[w*.5,h]],'#0d1029');
for(let lane=1;lane<=2;lane++){const topX=w*.5+(lane-1.5)*w*.11,bottomX=w*.5+(lane-1.5)*w*.34;for(let i=0;i<12;i++){let d=((i/12+game.roadOffset)%1);const y=h*.36+d*h*.7,spread=w*.34*(.12+.88*d),x=w*.5+(lane-1.5)*spread;ctx.fillStyle=`rgba(66,230,255,${.25+d*.6})`;ctx.fillRect(x-1.2*d,y,2.4*d,10*d+1);}}
for(let i=0;i<16;i++){const d=((i/16+game.roadOffset)%1),y=h*.36+d*h*.7,half=w*.16+d*w*.17;ctx.fillStyle=`rgba(246,60,218,${.05+d*.12})`;ctx.fillRect(w*.5-half,y,half*2,1+d*3);}
for(let i=0;i<5;i++){const x=(i*237+(t*game.speed*120)%w)%w,y=(i*73+Math.sin(t+i)*15)%(h*.38);ctx.fillStyle='#b9faff55';ctx.fillRect(x,y,1.5,8);}
}
function drawObject(o){const d=Math.max(.01,o.depth),x=laneX(o.lane,d),y=horizonY(d),scale=.18+d*1.14;ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);if(o.type==='coin'){const pulse=1+Math.sin(game.time*8+o.phase)*.12;ctx.scale(pulse,pulse);ctx.shadowBlur=22;ctx.shadowColor='#ffe66d';ctx.fillStyle='#ffe66d';ctx.beginPath();ctx.ellipse(0,-15,10,13,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff7bd';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#bd791f';ctx.fillRect(-2,-22,4,14);}
else if(o.type==='barrier'){ctx.shadowBlur=15;ctx.shadowColor='#ff58be';ctx.fillStyle='#ed489f';ctx.fillRect(-29,-34,58,31);ctx.fillStyle='#ffcaef';ctx.fillRect(-25,-31,50,4);ctx.fillStyle='#704176';ctx.fillRect(-23,-3,8,12);ctx.fillRect(15,-3,8,12);}
else if(o.type==='car'){ctx.shadowBlur=18;ctx.shadowColor='#51eaff';ctx.fillStyle='#174b78';ctx.beginPath();ctx.roundRect(-34,-52,68,52,10);ctx.fill();ctx.fillStyle='#5df5ff';ctx.beginPath();ctx.moveTo(-23,-36);ctx.lineTo(-15,-48);ctx.lineTo(15,-48);ctx.lineTo(24,-36);ctx.closePath();ctx.fill();ctx.fillStyle='#ff57d9';ctx.fillRect(-31,-9,10,4);ctx.fillRect(21,-9,10,4);}
else if(o.type==='laser'){ctx.shadowBlur=18;ctx.shadowColor='#fd3d73';ctx.fillStyle='#52385e';ctx.fillRect(-34,-54,7,55);ctx.fillRect(27,-54,7,55);ctx.fillStyle='#ff477a';ctx.fillRect(-31,-43,62,6);ctx.fillStyle='#ffe0ec';ctx.fillRect(-31,-42,62,2);}
else{const color=o.type==='shield'?'#55f7ff':o.type==='magnet'?'#ff70da':'#a4ff68';ctx.shadowBlur=20;ctx.shadowColor=color;ctx.strokeStyle=color;ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,-25,16,0,Math.PI*2);ctx.stroke();ctx.fillStyle=color;ctx.font='bold 17px sans-serif';ctx.textAlign='center';ctx.fillText(o.type==='shield'?'S':o.type==='magnet'?'M':'⚡',0,-19);}ctx.restore();}
function drawPlayer(){const p=game.player,x=laneX(p.laneVisual,.93),ground=horizonY(.93),jumpHeight=Math.sin((p.jump/.78)*Math.PI)*game.h*.12,y=ground-jumpHeight;ctx.save();ctx.translate(x,y);const sliding=p.slide>0;ctx.shadowBlur=19;ctx.shadowColor='#35eaff';ctx.fillStyle='#111a3f';if(sliding){ctx.beginPath();ctx.roundRect(-25,-29,49,22,10);ctx.fill();ctx.fillStyle='#43efff';ctx.fillRect(11,-24,19,5);}else{ctx.beginPath();ctx.roundRect(-17,-59,34,52,12);ctx.fill();ctx.fillStyle='#39e9f3';ctx.beginPath();ctx.roundRect(-12,-67,24,20,8);ctx.fill();ctx.fillStyle='#101633';ctx.fillRect(-8,-60,16,5);ctx.fillStyle='#ff55d5';ctx.fillRect(-12,-7,8,10);ctx.fillRect(5,-7,8,10);ctx.fillStyle='#f6b8ff';ctx.fillRect(-20,-44,5,19);ctx.fillRect(15,-44,5,19);}
if(game.player.shield>0){ctx.strokeStyle='#5cf7ff';ctx.lineWidth=2;ctx.globalAlpha=.55+Math.sin(game.time*9)*.18;ctx.beginPath();ctx.ellipse(0,-32,31,42,0,0,Math.PI*2);ctx.stroke();}ctx.restore();}
function drawParticles(){for(const q of game.particles){ctx.globalAlpha=Math.max(0,q.life*2);ctx.fillStyle=q.color;ctx.shadowBlur=9;ctx.shadowColor=q.color;ctx.fillRect(q.x,q.y,4,4);}ctx.globalAlpha=1;ctx.shadowBlur=0;}
function frame(now){const dt=Math.min(.04,(now-game.last)/1000||0);game.last=now;if(game.state==='playing')update(dt);drawBackground(game.time);if(game.state!=='menu'&&game.state!=='how'){game.objects.sort((a,b)=>a.depth-b.depth).forEach(drawObject);drawPlayer();drawParticles();}requestAnimationFrame(frame);}
document.querySelector('#start-button').addEventListener('click',startGame);document.querySelector('#again-button').addEventListener('click',startGame);document.querySelector('#how-button').addEventListener('click',()=>show('how'));document.querySelector('#how-back').addEventListener('click',()=>show('menu'));document.querySelector('#pause-button').addEventListener('click',togglePause);document.querySelector('#resume-button').addEventListener('click',togglePause);document.querySelector('#pause-menu-button').addEventListener('click',backToMenu);document.querySelector('#main-menu-button').addEventListener('click',backToMenu);
document.querySelectorAll('[data-action]').forEach(button=>button.addEventListener('pointerdown',event=>{event.preventDefault();act(button.dataset.action);}));window.addEventListener('keydown',event=>{const map={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'jump',Space:'jump',ArrowDown:'slide'};if(map[event.code]){event.preventDefault();act(map[event.code]);}if(event.code==='KeyP'||event.code==='Escape')togglePause();if(event.code==='Enter'&&game.state==='menu')startGame();});
let touchStart=null;canvas.addEventListener('touchstart',e=>{if(e.touches.length===1)touchStart={x:e.touches[0].clientX,y:e.touches[0].clientY};},{passive:true});canvas.addEventListener('touchend',e=>{if(!touchStart)return;const dx=e.changedTouches[0].clientX-touchStart.x,dy=e.changedTouches[0].clientY-touchStart.y;if(Math.max(Math.abs(dx),Math.abs(dy))>28)act(Math.abs(dx)>Math.abs(dy)?(dx<0?'left':'right'):(dy<0?'jump':'slide'));touchStart=null;},{passive:true});
window.addEventListener('resize',resize);document.addEventListener('visibilitychange',()=>{if(document.hidden&&game.state==='playing')togglePause();});resize();document.querySelector('#hud').style.display='none';requestAnimationFrame(frame);
